Add an option to use the memory sanitizer (ASAN) from gcc
There needed to be some refactoring in the cmakery because
1. we need to apply the sanitizer flag to all subdirs of parsec
2. we need to NOT APPLY the sanitizer to anything tool/frontend
(profiling, parsec_ptgpp, etc)
3. hence we may need to apply different options to parsec-base.a and the
parsec-base objects included from parsec.so

target_xxx_options do not propagate to object libraries that are
components of parsec.so

Because of the different build requirements, a blanket statement like
add_compile_options on the parsec directory is not a valid approach to
propagate them to all object libraries

object libraries are rendered mostly obsolete for subdir management in
cmake 3.13 thanks to the proper handling of relative paths in target_sources

Thus: we target_source from data_dist and from fortran subdirs, we do
not create object libraries anymore for these subparts. This avoids
having to do fine tracking of what flag gets applied where when doing a
target_xxx_options(parsec PRIVATE ...). It will now apply to everything,
except...

We still produce an object library for parsec-base. The benefit is that
we can reuse the TARGET_OBJECTS (compile only once) if the options on
parsec and parsec-base are the same. If not, we re-add the BASE_SOURCES
to force double compilation. This selection is more maintainable because
these options are set in the same CMakeFile.txt.

Signed-off-by: Aurelien Bouteiller <bouteill@icl.utk.edu>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -57,12 +57,15 @@ cat <<EOF
                 Enable Fortran bindings
 
 
---enable-debug=yes,paranoid,noisier|history|no
+--enable-debug=yes,paranoid,noisier|history,memaddr|memleak|memrace,no
                 turn on debugging information
                     yes:            normal debugging; some overhead
                     paranoid:       more thorough assertions; extra overhead
                     noisier:        more verbose debugging; heavy overhead
                     history:        keep an history of latest debugging messages in memory for gdb printing; light overhead
+                    memaddr:        use the memory sanitizer for out-of-bound detection
+                    memleak:        use the memory sanitizer for leak detection
+                    memrace:        use the memory sanitizer for thread-race detection
                     no (explicit):  remove all debugging symbols and assertions
 
 --enable-prof-trace
@@ -444,12 +447,15 @@ CMAKE_DEFINES+=" ${prefix:+-DCMAKE_INSTALL_PREFIX=$prefix}"
 if [ -z "$enable_debug" ]; then CMAKE_DEFINES+=" -DCMAKE_BUILD_TYPE=RelWithDebInfo"
 elif [[ "$enable_debug" =~ ^no$ ]]; then
     CMAKE_DEFINES+=" -DCMAKE_BUILD_TYPE=Release"
-elif [[ $enable_debug =~ ^((yes|paranoid|noisier|history),?)+$ ]]; then
+elif [[ $enable_debug =~ ^((yes|paranoid|noisier|history|memrace|memaddr|memleak),?)+$ ]]; then
     CMAKE_DEFINES+=" -DCMAKE_BUILD_TYPE=Debug"
     [[ $enable_debug =~ paranoid ]] && CMAKE_DEFINES+=" -DPARSEC_DEBUG_PARANOID=ON"
     [[ $enable_debug =~ noisier ]] && CMAKE_DEFINES+=" -DPARSEC_DEBUG_NOISIER=ON"
     [[ $enable_debug =~ history ]] && CMAKE_DEFINES+=" -DPARSEC_DEBUG_HISTORY=ON"
-else echo >&2 "Option $enable_debug is invalid (can be yes|paranoid|noisier|history|no)"; exit 1; fi
+    [[ $enable_debug =~ memrace ]] && CMAKE_DEFINES+=" -DPARSEC_DEBUG_MEM_RACE=ON"
+    [[ $enable_debug =~ memaddr ]] && CMAKE_DEFINES+=" -DPARSEC_DEBUG_MEM_ADDR=ON"
+    [[ $enable_debug =~ memleak ]] && CMAKE_DEFINES+=" -DPARSEC_DEBUG_MEM_LEAK=ON"
+else echo >&2 "Option $enable_debug is invalid (can be yes|paranoid|noisier|history|memrace|memaddr|memleak|no)"; exit 1; fi
 
 [ x$enable_prof_trace = xyes ] && CMAKE_DEFINES+=" -DPARSEC_PROF_TRACE=ON"
 [ x$enable_prof_trace = xno ] && CMAKE_DEFINES+=" -DPARSEC_PROF_TRACE=OFF"
